config/routes.rb
DiabloNumbers::Application.routes.draw do

  match "references", :to => "pages#references"
  match "definitions", :to => "pages#definitions"

  resource :class, :only => [] do
    collection do
      get :demon_hunter
    end
  end

  resources :topics, :only => [:index] do
    collection do
      get :dr_from_armor
    end
  end
  
  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController

  def demon_hunter
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @group_mechanics = {
      "Normal" => [
        { :health => 100, :damage => 100 },
        { :health => 175, :damage => 100 },
        { :health => 250, :damage => 100 },
        { :health => 325, :damage => 100 }
      ],
      "Nightmare" => [
        { :health => 100, :damage => 100 },
        { :health => 185, :damage => 105 },
        { :health => 270, :damage => 110 },
        { :health => 355, :damage => 115 }
      ],      
      "Hell" => [
        { :health => 100, :damage => 100 },
        { :health => 195, :damage => 110 },
        { :health => 290, :damage => 120 },
        { :health => 385, :damage => 130 }
      ],      
      "Inferno" => [
        { :health => 100, :damage => 100 },
        { :health => 210, :damage => 115 },
        { :health => 320, :damage => 130 },
        { :health => 430, :damage => 145 }
      ]      
    }

    @experience = {
      ">= +3" => { :percent => 125, :per_kill => true },
      "+2" => { :percent => 120, :per_kill => true },
      "+1" => { :percent => 115, :per_kill => true },
      "Same level" => { :percent => 100, :per_kill => true },
      "-1" => { :percent => 90, :per_kill => true },
      "-2" => { :percent => 80, :per_kill => true },
      "-3" => { :percent => 70, :per_kill => true },
      "-4" => { :percent => 60, :per_kill => true },
      "-5" => { :percent => 45, :per_kill => true },
      "-6" => { :percent => 30, :per_kill => false },
      "-7" => { :percent => 15, :per_kill => false },
      "-8" => { :percent => 5, :per_kill => false },
      "-9" => { :percent => 1, :per_kill => false }
    }
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def references
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
  end
  
  def dr_from_armor
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classes/_classes.html.haml
%table.table
  %thead
    %tr
      %td
        %h3 Classes
  %tbody
    %tr
      %td
        = link_to "Demon Hunter", demon_hunter_class_path
        %span.label.label-warning new!

app/views/classes/demon_hunter.html.haml
.row
  .span12
    .page-header
      %h1 Demon Hunter

/ .row
/   .span12
/     %h2 Things People Agree On
.row
  .span4
    %h3 Good Combinations
    %table.table.table-condensed.table-striped
      %thead
        %tr
          %th Skill
          %th Rune
      %tbody
        %tr
          %td Hungering Arrow
          %td
        %tr
          %td Elemental Arrow (ER)
          %td Nether Tenacles (NT)
        %tr
          %td Smoking Screen
          %td Lingering Fog
        %tr
          %td Evasive Fire (EF)
          %td Convering Fire (CF)

.row
  .span12
    %h2 Nvd's Inferno DH Tips
    .alert.alert-info
      Information came from post by Nvd on Diablo forums. You can read the original post
      = link_to "here", "http://us.battle.net/d3/en/forum/topic/5590639216"
      = "."

.row
  .span4
    %table.table
      %thead
        %tr
          %th Stat
          %th Value
      %tbody     
        %tr
          %td
            %strong Health
          %td 11k
        %tr
          %td
            %strong DPS
          %td 59k
        %tr
          %td
            %strong DPS + Sharpshooter
          %td 110k  
  .span6
    %blockquote
      %p My HP is so low because regardless of whether or not i have 50k or 1k hp, I get 1 shot in act 3/4 anyhow, so it really doesn't matter. Stack dex, don't get hit, EVER.
      %small Nvd 

.row
  .span6
    %table.table
      %thead
        %tr
          %th Builds
      %tbody
        %tr
          %td Boss Build
          %td= link_to "http://us.battle.net/d3/en/calculator/demon-hunter#aRXVTj!aeY!ZcZcZY", "http://us.battle.net/d3/en/calculator/demon-hunter#aRXVTj!aeY!ZcZcZY"
        %tr
          %td Act Build
          %td= link_to "http://us.battle.net/d3/en/calculator/demon-hunter#bRXVld!aYe!bbZcbY", "http://us.battle.net/d3/en/calculator/demon-hunter#bRXVld!aYe!bbZcbY"

.row
  .span12
    %h2 Surviving Hits
.row
  .span6
    %blockquote
      %p The reason you can't do Diablo without extreme gear is that you go for the pure DPS buiild. Swap for a tankier build for that encounter, making you able to survive a hit from the least avoidable attacks and you'll manage. 
      %br
      %p I know it seems futile to get enough resistances to live through an attack, but get both HP and resistances, and you'll be surprised.
      %small Iamawalrus

app/views/home/_armor.html.haml
.span3
  %h3 Armor

  %table.table.table-striped.table-condensed
    %tbody
      %tr
        %td
          1 
          %span.label.label-important strength
        %td.output_cell
          %i.icon-arrow-up
          1          
          %span.label.label-inverse armor  

app/views/home/_dr_from_armor.html.haml
.span4 
  %h3 Damage Reduction from Armor

  %table.table.table-striped.table-condensed
    %tbody
      %tr
        %td
          %span.label.label-inverse armor
          = "/"
          (
          %span.label.label-inverse armor
          = " + ( 50 * "
          %span.label monster level
          ) )
          

app/views/home/_dr_from_resists.html.haml
.span4 
  %h3 Damage Reduction from Resists

  %table.table.table-striped.table-condensed
    %tbody
      %tr
        %td
          %span.label.label-inverse resist
          = "/"
          (
          %span.label.label-inverse resist
          = " + ( 5 * "
          %span.label monster level
          ) )
      %tr
        %td
          %span.label.label-info intelligence
          = "/"
          (
          %span.label.label-info intelligence
          = " + ( 50 * "
          %span.label monster level
          ) )

app/views/home/_experience.html.haml
.span4
  %h2 
    Experience
    %small per monster killed  
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th{:style => "width:190px"}
          Monster level (mLvl) compared to character level            
        %th XP gain
    %tbody        
      - @experience.each_pair do |name, values|
        %tr
          %td= name
          %td.output_cell
            %span #{values[:percent]}% 
            - unless values[:per_kill]
              %span.label no +XP/kill from gear

app/views/home/_group_mechanics.html.haml
.row
  .span12
    %h2 
      Group Mechanics
      %small more is better
    .clearfix
.row
  - @group_mechanics.each_pair do |name, values|
    .span3
      %table.table.table-striped.table-condensed
        %thead
          %tr
            %th 
              %h3= name
            %th Health
            %th Damage

        %tbody
          - values.each_with_index do |numbers, index|
            %tr
              %td
                - (index + 1).times do
                  %i.icon-user
              %td #{numbers[:health]} %
              %td #{numbers[:damage]} %

app/views/home/_inferno_monster_level.html.haml
.span3
  %h2 
    Inferno Monster Levels
    %small 
  %table.table.table-condensed.table-striped
    %thead
      %tr
        %th Act
        %th Monster Level (mLvl)
    %tbody
      %tr
        %td I
        %td 61
      %tr
        %td II
        %td 62
      %tr
        %td III
        %td 63
      %tr
        %td IV
        %td 63

app/views/home/_resists.html.haml
.span3
  %h3 Resists

  %table.table.table-striped.table-condensed
    %tbody
      %tr
        %td
          1 
          %span.label.label-info intelligence
        %td.output_cell
          %i.icon-arrow-up
          = ".1"
          %span.label.label-inverse resist  

app/views/home/_vitality.html.haml
.span3 
  %h3 Vitality

  %table.table.table-striped.table-condensed
    %tbody
      %tr
        %td
          < Level 35            
        %td.output_cell
          36 + 4 x 
          %span.label level
          + 10 x
          %span.label.label-success vitality
      %tr
        %td >=Level 35            
        %td.output_cell
          (
          %span.label level
          = "- 25"
          )
          x
          %span.label.label-success vitality 

app/views/home/index.html.haml
.row
  .span12
    .alert.alert-info
      %h1.alert-heading
        Welcome to Diablo Numbers!
      %p{:style => "margin-top: 6px"}
        Like many of the people fighting their way through Diablo 3, I try to figure out how I should gear and what the stats mean. There are many smart blog posts, forum posts, and videos online. Here is my attempt to consolidate the best info into a fast, easy-to-digest format. A lot of this stuff currently is just copy and paste. 

      %p
        Please check out the 
        = link_to "references", references_path
        to see where I am getting the information.

.row
  .span6
    = render :partial => "classes/classes"
    
  .span6    
    = render :partial => "topics/topics"

.row
  = render "vitality"

.row
  = render "resists"
  = render "dr_from_resists"  
  
.row
  = render "armor"
  = render "dr_from_armor"

%hr
.row
  = render "experience"
  = render "inferno_monster_level"

%hr

= render "group_mechanics"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Diablo Numbers
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body  
  = render :partial => "shared/header"
  .container
    = render :partial => "shared/flash", :locals => { :flash => flash } 
    = yield

app/views/pages/definitions.html.haml
.row
  .span12
    %h1 
      Definitions
      %small what things mean

    %dl
      %dt Armor
      %dd Armor gives you % damage reduction against all types of damage, not just physical. It is increased by armor value on items, strength (1:1) and certain skills.

      %dt Diminishing Returns
      %dd The idea that an extra point in something (Armor) yields less return than the points before it. Ex. the 100 point in armor is less effective than the 99th point.

      %dt Effective Health
      %dd 
        Effective health is the amount of damage it takes to kill you (not to be confused with max health). If you have 1000 max health and 25% damage reduction, you have an effective health of 1333. You 
        can determine your effective health by the following formula: MaxHealth/(1-DamageReduction)
        %br
        %br
        %p
          This is where a lot of people get confused. Having 50% damage reduction does not allow you to take 50% more damage, it's a lot more than that. Consider this scenario: You have 1000 max health and 50% damage reduction. A monster is hitting you for 100 unmitigated damage, which only does 50 damage to you because you have 50% DR. It will take that monster 20 hits to kill you (1000 HP / 50 dmg) which means you can actually take 2,000 unmitigated damage (20 hits * 100 dmg). So with 50% DR you have 200% effective health, not 150%.

      %dt Monster Level (mLvl)
      %dd Stands for monster level. The level of the monster you're fighting.
      
      %dt Damage Reduction (DR)
      %dd Damage reduced (from armor).

app/views/pages/references.html.haml
.row
  .span12
    .page-header
      %h1 
        References
        %small or where the hell we got our numbers...

.row
  .span6
    %table.table
      %thead
        %tr
          %th
            %h3 General
      %tbody    
        %tr
          %td= link_to "http://mmo-mechanics.com/swtor/forums/Thread-Diablo-3-formula-list", "http://mmo-mechanics.com/swtor/forums/Thread-Diablo-3-formula-list"
        %tr
          %td= link_to "http://us.battle.net/d3/en/forum/topic/5149150485", "http://us.battle.net/d3/en/forum/topic/5149150485"
        %tr
          %td= link_to "http://www.youtube.com/watch?v=K9uVdmdzfb0&feature=youtu.be", "http://www.youtube.com/watch?v=K9uVdmdzfb0&feature=youtu.be"
        %tr
          %td= link_to "http://www.reddit.com/r/Diablo/comments/u9u0w/some_analysis_on_the_relative_values_of_resist/", "http://www.reddit.com/r/Diablo/comments/u9u0w/some_analysis_on_the_relative_values_of_resist/"

.row
  .span6
    %table.table
      %thead
        %tr
          %th
            %h3 Demon Hunter
      %tbody
        %tr
          %td= link_to "http://us.battle.net/d3/en/forum/topic/5590639216", "http://us.battle.net/d3/en/forum/topic/5590639216"
        %tr
          %td= link_to "http://us.battle.net/d3/en/forum/topic/5575468356", "http://us.battle.net/d3/en/forum/topic/5575468356"

app/views/shared/_flash.html.haml
#flash
  - if flash.any?
    .row-fluid
      .span2
        &nbsp;
      .span8
        - flash.each do |kind, message|
          - if kind == :success
            .alert.alert-success
              = link_to "x", "#", :class => "close"
              %p= message
          - if kind == :notice
            .alert.alert-info
              = link_to "x", "#", :class => "close"
              %p= message
          - if kind == :alert
            .alert
              = link_to "x", "#", :class => "close"
              %p= message
          - if kind == :error
            .alert.alert-error
              = link_to "x", "#", :class => "close"
              %p= message          

app/views/shared/_footer.html.haml
%footer.footer
  .container-fluid
    .row-fluid

app/views/shared/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Diablo Numbers", root_path, :class => "brand"

      %ul.nav
        %li= link_to "Definitions", definitions_path
        %li= link_to "Topics", topics_path
        %li= link_to "Demon Hunter", demon_hunter_class_path
        %li= link_to "References", references_path

app/views/topics/_topics.html.haml
%table.table
  %thead
    %tr
      %th
        %h3 Topics
  %tbody
    %tr
      %td
        = link_to "Damage Reduction from Armor", dr_from_armor_topics_path
        %span.label.label-warning new!

app/views/topics/dr_from_armor.html.haml
.page-header
  %h1 Damage Reduction from Armor
  
.row
  .span12
    
    .alert.alert-info
      This information is a direct copy from a post by TBD in the Diablo 3 forums. You can see the original post
      = link_to "here", "http://us.battle.net/d3/en/forum/topic/5149150485"
      = "."
    .well
      %h3 DR from Armor = Armor / ( Armor + (50 * mLvl) )
      %p
        As you can see, there is a constant in the bottom (50*mLvl). Armor is being divided by (Armor + 3000). It will always approach but never reach 1 because Armor can never be greater than or equal to (Armor + positive integer).

.row
  .span4
    = link_to "http://i50.tinypic.com/1pgtaf.jpg", :target => "_blank" do
      = image_tag "http://i50.tinypic.com/1pgtaf.jpg"
  .span6.dr_chart_description
    %p
      As you can see, there is a constant in the bottom (50*mLvl). Armor is being divided by (Armor + 3000). It will always approach but never reach 1 because Armor can never be greater than or equal to (Armor + positive integer).
    %p
      The graph shows that as armor increases, additional points in armor yield less and less DR. Most people call this diminishing returns and explain that the more armor you have the less additional armor is worth. That is wrong. 

.row
  .span4
    = link_to "http://i47.tinypic.com/21d1u87.jpg", :target => "_blank" do
      = image_tag "http://i47.tinypic.com/21d1u87.jpg"
  .span6.dr_chart_description
    %p
      The reason it is wrong is because the effect of each additional point of DR is more powerful than the last. So in order to keep the effectiveness of armor linear, each point must must yield less damage reduction because each point of damage reduction is more effective than the last.
.row
  .span4  
    = link_to "http://i49.tinypic.com/20ge53r.jpg", :target => "_blank" do
      = image_tag "http://i49.tinypic.com/20ge53r.jpg"
  .span6.dr_chart_description
    %p
      To further illustrate my last point lets look at an example:
      At 70% DR you have an effective health of 333.3%, increase over last = 10.8%
      At 71% DR you have an effective health of 344.8%, increase over last = 11.5%
      At 72% DR you have an effective health of 357.1%, increase over last = 12.3%
      = "..."
      At 95% DR you have an effective health of 2000%, increase over last = 333.35%
      At 96% DR you have an effective health of 2500%, increase over last = 500%    

app/views/topics/index.html.haml
.row
  .span12
    .page-header
      %h1 Current Topics
    = render :partial => "topics/topics"